name: details and data
title: details and data
description: I'm a student and a researcher. I write data-driven posts about science, people, and animals.
url: http://mackfinkel.com
author: Mack Finkel
future: true

subscribe:
  - name: rss
    url: feed.xml

social:
  - name: twitter
    url: https://twitter.com/mackfinkel
    
sidebar:
  - title: i'm very social
    subfolderitems:
      - name: twitter
        url: https://twitter.com/mackfinkel
      - name: github
        url: https://github.com/mackfinkel
      - name: steemit
        url: https://steemit.com/@somethingburger/
      - name: linkedin
        url: https://www.linkedin.com/in/mack-finkel-187849145
  - title: subscribe
    subfolderitems:
      - name: rss
        url: feed.xml
  - title: contact
    subfolderitems:
      - name: mackfinkel [at] gmail [dot] com

plugins:
  - jekyll-sitemap